a = float(input("Enter 1st num: "))
b = float(input("Enter 2nd num: "))
c = float(input("Enter 3rd num: "))
d = float(input("Enter 4th num: "))

print("\n= Here is the output =")
print("1st + 3rd + 2nd * 1st =", a + c + b * a)
print("2nd - 3rd / 1st =", b - c / a if a else "Undefined")
print("4th + 1st * 4th =", d + a * d)
print("1st / 2nd + 3rd * 4th =", a / b + c * d if b else "Undefined")
print("4th + 2nd =", d + b)
