m = float(input("Enter 1st num: "))
a = float(input("Enter 2nd num: "))
p = float(input("Enter 3rd num: "))
i = float(input("Enter 4th num: "))

print("\n= Here is the output =")
print("1st + 3rd + 2nd * 1st =", m + p + a * m)
print("2nd - 3rd / 1st =", a - p / i if m else "Undefined")
print("4th + 1st * 4th =", i + m * i)
print("1st / 2nd + 3rd * 4th =", m / a + p * i if a else "Undefined")
print("4th + 2nd =", i + a)
